### ISSUE TITLE
Ins't not a issue 

### ISSUE THREAD

**Issue by miltlima** [FusionAuth/fusionauth-quickstart-go-api#4] opened 2024-09-05 18:22 UTC
I have been building an application with Golang that depends on fusionauth, im using the 1.15.8 version, I try to send a POST do create a Tenant, but I receive error 400, I already check all things and sent this payload, someone could share the API doc from this fusionauth version ? 

```json

{
    "tenant": {
        "emailConfiguration": {
            "host": "notused.com",
            "port": 1001,
            "security": "NONE",
            "verifyEmail": false,
            "verifyEmailWhenChanged": false
        },
        "eventConfiguration": {
            "events": {
                "jwt.public-key.update": {
                    "enabled": false,
                    "transactionType": "None"
                },
                "jwt.refresh-token.revoke": {
                    "enabled": false,
                    "transactionType": "None"
                },
                "user.bulk.create": {
                    "enabled": false,
                    "transactionType": "None"
                },
                "user.create": {
                    "enabled": false,
                    "transactionType": "None"
                },
                "user.deactivate": {
                    "enabled": false,
                    "transactionType": "None"
                },
                "user.delete": {
                    "enabled": false,
                    "transactionType": "None"
                },
                "user.login.failed": {
                    "enabled": false,
                    "transactionType": "None"
                },
                "user.login.success": {
                    "enabled": false,
                    "transactionType": "None"
                },
                "user.reactivate": {
                    "enabled": false,
                    "transactionType": "None"
                },
                "user.registration.create": {
                    "enabled": false,
                    "transactionType": "None"
                },
                "user.registration.delete": {
                    "enabled": false,
                    "transactionType": "None"
                },
                "user.registration.update": {
                    "enabled": false,
                    "transactionType": "None"
                },
                "user.update": {
                    "enabled": false,
                    "transactionType": "None"
                }
            }
        },
        "externalIdentifierConfiguration": {
            "authorizationGrantIdTimeToLiveInSeconds": 30,
            "changePasswordIdGenerator": {
                "length": 32,
                "type": "randomBytes"
            },
            "changePasswordIdTimeToLiveInSeconds": 600,
            "deviceCodeTimeToLiveInSeconds": 1800,
            "deviceUserCodeIdGenerator": {
                "length": 6,
                "type": "randomAlphaNumeric"
            },
            "emailVerificationIdGenerator": {
                "length": 32,
                "type": "randomBytes"
            },
            "emailVerificationIdTimeToLiveInSeconds": 86400,
            "externalAuthenticationIdTimeToLiveInSeconds": 300,
            "oneTimePasswordTimeToLiveInSeconds": 60,
            "passwordlessLoginGenerator": {
                "length": 32,
                "type": "randomBytes"
            },
            "passwordlessLoginTimeToLiveInSeconds": 180,
            "registrationVerificationIdGenerator": {
                "length": 32,
                "type": "randomBytes"
            },
            "registrationVerificationIdTimeToLiveInSeconds": 86400,
            "setupPasswordIdGenerator": {
                "length": 32,
                "type": "randomBytes"
            },
            "setupPasswordIdTimeToLiveInSeconds": 86400,
            "twoFactorIdTimeToLiveInSeconds": 300,
            "twoFactorTrustIdTimeToLiveInSeconds": 2592000
        },
        "failedAuthenticationConfiguration": {
            "actionDuration": 3,
            "actionDurationUnit": "MINUTES",
            "resetCountInSeconds": 60,
            "tooManyAttempts": 5
        },
        "familyConfiguration": {
            "allowChildRegistrations": true,
            "deleteOrphanedAccounts": false,
            "deleteOrphanedAccountsDays": 30,
            "enabled": false,
            "maximumChildAge": 12,
            "minimumOwnerAge": 21,
            "parentEmailRequired": false
        },
        "httpSessionMaxInactiveInterval": 3600,
        "issuer": "hom.local",
        "jwtConfiguration": {
            "accessTokenKeyId": "00000-00000-0000-00000-0000000",
            "enabled": true,
            "idTokenKeyId": "000000-00000-000000-00000-000000",
            "refreshTokenTimeToLiveInMinutes": 43200,
            "timeToLiveInSeconds": 86400
        },
        "maximumPasswordAge": {
            "days": 15,
            "enabled": true
        },
        "minimumPasswordAge": {
            "enabled": false,
            "seconds": 30
        },
        "name": "ws-company",
        "passwordEncryptionConfiguration": {
            "encryptionScheme": "salted-pbkdf2-hmac-sha256",
            "encryptionSchemeFactor": 24000,
            "modifyEncryptionSchemeOnLogin": false
        },
        "passwordValidationRules": {
            "breachDetection": {
                "enabled": false
            },
            "maxLength": 256,
            "minLength": 8,
            "rememberPreviousPasswords": {
                "count": 3,
                "enabled": true
            },
            "requireMixedCase": true,
            "requireNonAlpha": true,
            "requireNumber": true,
            "validateOnLogin": false
        },
        "themeId": "700000-000000-00000000-000000000000",
        "userDeletePolicy": {
            "unverified": {
                "enabled": false,
                "numberOfDaysToRetain": 0
            }
        }
    }
}

```

**Comment by mooreds** [comment] 2024-09-05 18:30
Hi @miltlima . That version is [over 4 years old](https://fusionauth.io/docs/release-notes/archive#version-1-15-8). Would suggest upgrading.

If that is not possible, I'd probably look at the wayback machine. I didn't find a version of the website from 2020 in archive.is, though.

You can also look at our website from 2020 in GH. This tag might help: https://github.com/FusionAuth/fusionauth-site/tree/3.0.0

I'm going to close this issue because it is a request for support, not a bug.

Here's the best place to go for support: https://fusionauth.io/community/forum/ (unless you have a paid plan, in which case you should open a support ticket).

**Closed as completed by mooreds** 2024-09-05 18:30 UTC

**Comment by miltlima** [comment] 2024-09-09 12:54
@mooreds thank you !
